on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build-linux:
    runs-on: [ubuntu-20.04]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build docker image
        run: |
          docker build --memory=5g -f .github/dockerfiles/Dockerfile.builder -t intel-xpumanager .
      - name: Run build.sh
        run: |
          rm -fr build
          docker run -v ${{ github.workspace }}:/workspace intel-xpumanager bash -c "cd /workspace && ./build.sh"
      - name: Check if build succeeded
        run: |
          set -e
          if ls "${{ github.workspace }}/build"/*.deb >/dev/null 2>&1; then
            echo "Package exists."
          else
            echo "Package does not exist."
            exit 1
          fi
